# Generated by Django 3.2.8 on 2021-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
